#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..", "..");
const skillsDir = path.join(root, "skills", "architekt-wnetrz");
const mainPath = path.join(skillsDir, "SKILL.md");
const refsDir = path.join(skillsDir, "references");
const outFile = path.join(__dirname, "..", "src", "skill-content.generated.ts");

if (!fs.existsSync(mainPath)) {
  console.error(`SKILL.md not found at ${mainPath}`);
  process.exit(1);
}

const main = fs.readFileSync(mainPath, "utf8");
const refs = fs
  .readdirSync(refsDir)
  .filter((f) => f.endsWith(".md"))
  .sort()
  .map((f) => ({ name: f, content: fs.readFileSync(path.join(refsDir, f), "utf8") }));

const header =
  "// AUTO-GENERATED by scripts/build-skill.mjs — do not edit by hand.\n" +
  `// Source: ${path.relative(path.dirname(outFile), skillsDir)}\n\n`;

const ts =
  header +
  `export const SKILL_MAIN: string = ${JSON.stringify(main)};\n\n` +
  `export const SKILL_REFS: Record<string, string> = ${JSON.stringify(
    Object.fromEntries(refs.map((r) => [r.name, r.content])),
    null,
    2,
  )};\n`;

fs.writeFileSync(outFile, ts);
const kb = (ts.length / 1024).toFixed(1);
console.log(`Wrote ${outFile} (${kb} KB, ${refs.length} reference files)`);
